### ISSUE TITLE
Internal references in ACC

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/ACC#3]
Please have a look at the following entry from ACC
```
<L>48195<pc>3-158,2<k1>hfdayadeSika<k2>hfdayadeSika
{#hfdayadeSika#}¦ <ab type="pers">author</ab> of Siddhāntadīpa. Mentioned by Veda-
<>jñāna in Ātmārthapūjāpaddhati. <ls>Hz</ls>. 2 p. 106.
```
In this case
`sidDAntadIpa#vedajYAna#AtmArTapUjApadDati`
These three items are headwords of ACC and also occur in the entry.
It is desirable that such internal references may be tagged, so that they can be hyperlinked later on.
I have started such a work and have found out a way to identify and segregate such words. Now only modality to replace the existing text with tagged text remains.

`Veda\n<>jñāna` is a typical example. The breaks occur randomly anywhere in the words. So, a modality has to be created that ignores such word breaks while making replacements, otherwise vedajYAna will be missed if we go line by line.

**Comment by gasyoun** [comment]
> The breaks occur randomly anywhere in the words. So, a modality has to be created that ignores such word breaks while making replacements, otherwise vedajYAna will be missed if we go line by line.

Step 1.

> references may be tagged, so that they can be hyperlinked later on.

Step 2.

That's like adding a new layer, making for the first time the file more than just a printed book.

**Comment by drdhaval2785** [comment]
Did some tweaking.
`<ab type="hw" value="spellingInSlp">spellingInIast</ab>` is the tagging pattern.
Now the sample output looks like the following
```
<L>1233<pc>1-032,1<k1>alaMkAratilaka<k2>alaMkAratilaka
{#alaMkAratilaka#}¦ by <ab type="hw" value="BAnudatta">Bhānudatta</ab>. <ls>Burnell</ls> 54^a.
<HI>--by <ab type="hw" value="vAgBawa">Vāgbhaṭa</ab>. <ls>IO</ls>. 2543. <ls>Kh</ls>. 71. <ls>B</ls>. 3, 44. <ls>W</ls>. 1717.
<HI>--by Śrīkaramiśra. <ls>Khn</ls>. 52.
<L>1235<pc>1-032,1<k1>alaMkAradAnaviDi<k2>alaMkAradAnaviDi
{#alaMkAradAnaviDi#}¦ from <ab type="hw" value="brahmavEvartapurARa">Brahmavaivartapurāṇa</ab>. <ls>Ben</ls>. 141.
<L>1236<pc>1-032,1<k1>alaMkAranikarza<k2>alaMkAranikarza
{#alaMkAranikarza#}¦ <ab type="subj">alaṃk</ab>. by <ab type="hw" value="suDendra">Sudhendra</ab>. <ls>Oppert</ls> 4797.
<L>1237<pc>1-032,1<k1>alaMkAramaYjarI<k2>alaMkAramaYjarI
{#alaMkAramaYjarI#}¦ Quoted by <ab type="hw" value="ruyyaka">Ruyyaka</ab>. <ls>Oxf</ls>. 210^a.
<HI>--by <ab type="hw" value="trimalla">Trimalla</ab> <ab type="hw" value="Bawwa"><ab type="hw" value="Bawwa">Bhaṭṭa</ab></ab>. <ls>Oudh</ls> XIV, 44. <ls>NP</ls>. II, 122.
<><ls>Bühler</ls> 542.
<HI>--by Nirmala <ab type="hw" value="Bawwa"><ab type="hw" value="Bawwa">Bhaṭṭa</ab></ab>. <ls>Oudh</ls> IV, 13.
<L>1238<pc>1-032,1<k1>alaMkAramaYjarIwIkA<k2>alaMkAramaYjarIwIkA
{#alaMkAramaYjarIwIkA#}¦ <ab type="hw" value="maDuDArA">Madhudhārā</ab>, by Sudhīndra Yati.
<><ls>Burnell</ls> 57^a.
<L>1241<pc>1-032,1<k1>alaMkAramuktAvalI<k2>alaMkAramuktAvalI
{#alaMkAramuktAvalI#}¦ by <ab type="hw" value="lakzmIDara">Lakṣmīdhara</ab>. <ls>K</ls>. 98. <ls>B</ls>. 3, 44.
<HI>--by <ab type="hw" value="viSveSvara">Viśveśvara</ab>. <ls>NW</ls>. 608.
<L>1242<pc>1-032,1<k1>alaMkArayAnaka<k2>alaMkArayAnaka
{#alaMkArayAnaka#}¦ <ab type="subj">jy</ab>. by <ab type="hw" value="gopAladeva">Gopāladeva</ab>. <ls>Rādh</ls> 33.
<L>1243<pc>1-032,1<k1>alaMkAraratnAkara<k2>alaMkAraratnAkara
{#alaMkAraratnAkara#}¦ <ab type="subj">alaṃk</ab>. <ls>Burnell</ls> 54^a.
<HI>--by <ab type="hw" value="SoBAkaramitra">Śobhākaramitra</ab>. <ls>Report</ls> XV. <ls>H</ls>. 170. <ls>Peters</ls>.
<>1, 12.
<HI1><symbol n="C.">C.</symbol> Alaṃkāraratnākarodāharaṇa by the same. Re-
<>port XVI.
<HI1>Alaṃkāraratnākarodāharaṇasaṃnibaddha-Devisto-
<>tra by <ab type="hw" value="yaSaskara">Yaśaskara</ab>. <ls>L</ls>. 1822. <ls>Report</ls> IX. <ls>Peters</ls>.
<>1, 116.
<L>1244<pc>1-032,1<k1>alaMkArarAGava<k2>alaMkArarAGava
{#alaMkArarAGava#}¦ by <ab type="hw" value="yajYeSvara">Yajñeśvara</ab> Dīkṣita. <ls>Burnell</ls> 54^a.
<><ls>Oppert</ls> 1755.
<L>1245<pc>1-032,1<k1>alaMkAravimarSinI<k2>alaMkAravimarSinI
{#alaMkAravimarSinI#}¦ See <ab type="hw" value="alaMkArasarvasva">Alaṃkārasarvasva</ab>.
```

**Comment by funderburkjim** [comment]
For reference, here is the coding currently in acc5 and acc6 for the hfdayadeSika headword example,
where there is an important line-break to take into account.
```
acc5.txt
<L>48195<pc>3-158,2<k1>hfdayadeSika<k2>hfdayadeSika
{#hfdayadeSika#}¦ <ab type="pers">author</ab> of Siddhāntadīpa. Mentioned by Veda-
<>jñāna in Ātmārthapūjāpaddhati. <ls>Hz</ls>. 2 p. 106.
<LEND>

acc6.txt
<L>48195<pc>3-158,2<k1>hfdayadeSika<k2>hfdayadeSika
{#hfdayadeSika#}¦ <ab type="pers">author</ab> of <ab type="hw" value="sidDAntadIpa">Siddhāntadīpa</ab>. Mentioned by <ab type="hw" value="vedajYAna">Veda-
<>jñāna</ab> in <ab type="hw" value="AtmArTapUjApadDati">Ātmārthapūjāpaddhati</ab>. <ls>Hz</ls>. 2 p. 106.
```

The solution:
* keeps the original line-break of the text in the 'non-markup' 
* adds a an 'ab' tag with value of 'type' attribute equal to 'hw', and
  value of 'value' attribute equal to the SLP1 spelling of the full word, including hyphenation.
* The same form also applies to non-hyphenated internal references.

I don't see any problem with this.  It should convert well to xml;  and the xml could handle the
line-break either by maintaining the break or not, as desired.
Will need to do full modification with make_xml.py to be sure no hidden gotchas, but it looks like
a good solution for now.

**Comment by funderburkjim** [comment]
### missing `<LEND>`

acc6.txt forgot to put the <LEND> record in.  This needs to be corrected.

**Comment by funderburkjim** [comment]
### are all the 'value' values ACC headwords?

In the markup, the value of the 'value' attribute is an slp1 spelling of the 'ab' text (this text represents a Sanskrit word in IAST coding).

It needs to be checked that this SLP1 spelling is a headword of ACC.

I suspect that there will be some (hopefully few) of these SLP1 spellings that are NOT ACC headwords.
We'll need to understand how many such cases occur, and what the reasons are.

**Comment by funderburkjim** [comment]
@drdhaval2785  

I think it remains to deal with the ramifications of the acc4-6.txt markup in acc.xml.
In particular, modifications may be needed for:
* acc.dtd   definitely
* make_xml.py  maybe
* web/webtc/disp.php   definitely
   * optional whether to add display features to exhibit the markup.
* acc-meta2.txt  definitely

**Comment by drdhaval2785** [comment]
>missing LEND

Yes. My fault. Correcting it.

>are all the 'value' values ACC headwords?

Yes. That was the precondition for tagging. The word under examination was stripped of tags and line breaks etc and the resultant word was converted to SLP1 and then checked whether it is in headword list or not. Only if it is in headword list, it was tagged.

**Comment by funderburkjim** [comment]
> Only if it is in headword list
Excellent.

**Comment by gasyoun** [comment]
> web/webtc/disp.php definitely

Based on MW or PW.

**Comment by drdhaval2785** [comment]
Internal headwords referenced in acc6.txt.
Now whatever remains is cleanup and manual correction.
Closing this issue.
